[ADD]: feature/search
wecode-bootcamp-korea/44-2nd-Chill-Play-backend pull request #6
Opened 2023-04-25 12:20 UTC by lsg622

## :: 최근 작업 주제 (하나 이상의 주제를 선택해주세요.)
- [ ] 기능 추가
- [ ] 데이터베이스 작업
- [ ] 리팩토링
- [ ] 버그 수정
- [ ] 컨벤션 수정

<br />

## :: 구현 목표 - 해당 브랜치(PR)에서 구현하고자 하는 하나의 목표 작성
- 뮤지컬 검색 기능 구현

<br />

## :: 구현 사항 설명 - 해당 브랜치(PR)에서 작업한 내용 작성
- 뮤지컬 이름 키워드 입력시, 관련 데이터 가져오는 기능 구현.

<br />

## :: 테스트 결과 이미지
1. Server가 잘 동작하는지 확인할 수 있는 Terminal 캡쳐 이미지
2. Postman(Client Tool)을 이용한 API 테스트 결과 이미지
3. 작성한 Test Code가 잘 통과했는지 확인할 수 있는 이미지
4. DB 작업 PR인 경우 Table 생성 및 수정 결과에 대해 확인할 수 있는 이미지

<br />
<img width="764" alt="스크린샷 2023-04-25 오후 9 17 33" src="https://user-images.githubusercontent.com/123074891/234273938-92983b46-8f28-40f5-825c-745b6a320362.png">
![스크린샷 2023-04-25 오후 9 18 18](https://user-images.githubusercontent.com/123074891/234273951-c70f9700-9655-4a22-a04b-72ee016e4437.png)
<img width="797" alt="스크린샷 2023-04-25 오후 9 17 26" src="https://user-images.githubusercontent.com/123074891/234273958-5487f8a4-167c-4337-beaf-afa8c1895aef.png">

## :: 기타 질문 및 특이 사항
- 제가 작성한 함수의 로직이 너무 복잡하다고 생각이 됩니다. 더 효율적인 방법이 없을까요? (예시)

2023-04-26 01:43 UTC, kyeongraekim requested changes

2023-04-26 01:43 UTC, kyeongraekim commented on controllers/musicalController.js
> +console.log(req.query)
- 불필요한 콘솔로깅은 푸시전 꼭 삭제해주세요!

2023-04-26 01:43 UTC, kyeongraekim commented on controllers/musicalController.js
> +const searchMusical = catchAsync(async (req, res) => {
- 함수명 네이밍 컨벤션에서는 searchMuscialByName정도로 어떤 내용을 기준으로 해당 데이터를 끌고 오는지 그 기준점을 명확히 표현해주세요!~

2023-04-26 01:43 UTC, kyeongraekim commented on models/musicalDao.js
> +    let musicals = await appDataSource.query(
- let 이 아닌 Const 로 해당 변수를 선언해주세요!
- 보다 엄격한 변수 관리를 위해서 재할당 등이 가능한 let 의 사용은 꼭 필요한 순간을 제외하고는 사용을 지양해주셔야 합니다.

2023-04-26 01:43 UTC, kyeongraekim commented on tests/tests/musicals.test.js
> +  test("SUCCESS: searched musical", async () => {
- test description은 실제 어떠한 형태로 해당 테스트를 시험하는 것인지 명확히 드러내야 합니다. "SUCCESS: search musical by musical name / keyword " 정도로 구체적으로 표현해서 제 3자가 어떠한 변수에서의 테스팅 코드인지 명시 해주세요!

2023-04-26 01:43 UTC, kyeongraekim commented on tests/tests/musicals.test.js
> +  test("SUCCESS: searched musical", async () => {
- 해당 내용은 키워드 검색 입력이 안되었을 때 전체 뮤지컬 리스트를 불러오는 테스트일까요? 해당 내용의 묘사도 description  내역에 작성해주세요!

2023-04-26 01:43 UTC, kyeongraekim commented on tests/tests/musicals.test.js
> + test("SUCCESS: searched musical", async () => {
- 해당 내용은 이미 키워드로 검색하는 내역이 첫 번째로 작성된 테스트에서 잘 검증되고 있는 것 같습니다.
- 따라서 불필요한 중복 테스트로 보이며, 이제는 테스트의 성공 케이스만이 아닌 실패/예외 케이스 도 추가해서 올려주세요!

2023-04-26 11:36 UTC, lsg622 commented
말씀하신 git Rebase 적용하여 push 했습니다. 확인 부탁 드립니다!

2023-04-27 01:12 UTC, kyeongraekim requested changes

2023-04-27 01:12 UTC, kyeongraekim commented on models/musicalDao.js
> +      throw err;}
- 가독성을 위해서 아래와 같이 부정형 operator를 써보는 것은 어떠실까요?

```javascript 
    if (!matchingMusicals.length) {
      throw new CustomError('404', 'NOT_FOUND');
    }

2023-04-27 01:12 UTC, kyeongraekim commented on tests/tests/musicals.test.js
> + test("FAILED: can't found musical by inputing musical name/keyword", async () => {
- found -> find 간단한 영어 문법 오류가 보이네요!~

2023-04-27 01:12 UTC, kyeongraekim commented on models/musicalDao.js
> +      throw err;}
- offset limit 값을 받아서 불필요하게 많은 데이터를 클라이언트에게 전달하지 않도록 미연에 방지해주세요.

2023-04-27 01:12 UTC, kyeongraekim commented on models/musicalDao.js
> +      throw err;}
- 필요하다면 default offset , limit 설정까지 상수변수에 담아서 관리해주세요

2023-04-27 09:15 UTC, kyeongraekim approved these changes
LGTM!~

2023-04-28 06:55 UTC, merged