[ADD] 뮤지컬 필터 기능 추가
wecode-bootcamp-korea/44-2nd-Chill-Play-backend pull request #7
Opened 2023-04-25 14:14 UTC by wkh24

## :: 최근 작업 주제 (하나 이상의 주제를 선택해주세요.)
- [ ] 기능 추가
- [ ] 데이터베이스 작업
- [ ] 리팩토링
- [ ] 버그 수정
- [ ] 컨벤션 수정

<br />

## :: 구현 목표 - 해당 브랜치(PR)에서 구현하고자 하는 하나의 목표 작성
- email, password를 이용한 로그인 기능 구현 (예시)

<br />

## :: 구현 사항 설명 - 해당 브랜치(PR)에서 작업한 내용 작성
- API 호출 시 필요한 값들에 대한 유효성 검사 (예시)

<br />

## :: 테스트 결과 이미지
1. Server가 잘 동작하는지 확인할 수 있는 Terminal 캡쳐 이미지
2. Postman(Client Tool)을 이용한 API 테스트 결과 이미지
3. 작성한 Test Code가 잘 통과했는지 확인할 수 있는 이미지
4. DB 작업 PR인 경우 Table 생성 및 수정 결과에 대해 확인할 수 있는 이미지

<br />

## :: 기타 질문 및 특이 사항
- 제가 작성한 함수의 로직이 너무 복잡하다고 생각이 됩니다. 더 효율적인 방법이 없을까요? (예시)

2023-04-26 01:30 UTC, kyeongraekim requested changes
해당 내용에 대한 유닛테스트도 함께 추가하여 올려주세요!~

2023-04-26 01:30 UTC, kyeongraekim commented on controllers/musicalController.js
> +const musicalList = catchAsync(async (req, res) => {
- 함수명 네이밍 컨벤션은 정확한 CRUD 의도가 드러날 수 있게 해주셔야 합니다. 
- getAllMusicalList 정도로 수정해도 좋을 것 같습니다.

2023-04-26 01:30 UTC, kyeongraekim commented on models/musicalDao.js
> +    };
- 혹시 이 부분은 팀내에서 사용할 쿼리빌더의 형태로 기획 구성 계획이 있으실까요?

2023-04-27 14:41 UTC, wkh24 commented
api는 완성돼서 프론트측이랑 통신까지 완료됐습니다. 테스트코드는 다시 작성해서 올리겠습니다.

2023-04-28 01:37 UTC, kyeongraekim approved these changes
LGTM!~ 테스트 코드를 이어서 꼭 빠르게 올려주세요!~

2023-04-28 01:37 UTC, merged